import eslint from '@eslint/js';
import prettier from 'eslint-config-prettier';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';

/**
 * Components do not call fetch — they call a hook from a feature's queries.ts.
 * Anything else bypasses the single-flight refresh, the retry policy and the
 * cache. This is what makes that structural rather than aspirational.
 */
const apiClientBoundary = {
  group: ['**/api/client', '**/api/auth-fetch', '**/api/schema'],
  message: 'Import a hook from the feature\'s queries.ts instead. See CLAUDE.md, "Architecture".',
};

/**
 * The app and the proxy Worker compile against different global `Request`,
 * `Response` and `fetch` types, in two tsconfig projects that cannot see each
 * other. That stops the *types* mixing; this stops the *code* mixing, which is
 * what would otherwise produce an import that lints clean and fails to build.
 */
const workerBoundary = {
  group: ['**/worker', '**/worker/**'],
  message:
    'src/worker/ is Workers runtime code and shares nothing with the app. See CLAUDE.md, "The tsconfig split".',
};

/*
 * Started from the server's config verbatim, then added the React plugins and
 * five rules that turn CLAUDE.md prose into something the build enforces.
 *
 * Those five are worth reading before changing: each one exists because the
 * failure it prevents is silent, and expensive, and would otherwise rest on
 * somebody remembering a paragraph.
 */
export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'coverage/**',
      'node_modules/**',
      '.wrangler/**',
      // Generated by `wrangler types` (`npm run cf-typegen`).
      'worker-configuration.d.ts',
      // Generated by `npm run api:types` from the server's openapi.yaml.
      'src/api/schema.d.ts',
    ],
  },
  eslint.configs.recommended,
  tseslint.configs.strictTypeChecked,
  tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        // Resolves each file to the nearest tsconfig that includes it, so
        // type-aware linting works across every project without extra config.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-unnecessary-condition': 'error',
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/require-await': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-console': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],

      /*
       * Nothing from this app may be written to disk.
       *
       * The highest-consequence rule in the charter, and until now enforced
       * only by memory. A referral holds a name, an address, a phone number and
       * a reason for needing food; a draft saved "helpfully" to localStorage
       * leaves it on a shared church-hall laptop for the next person.
       */
      'no-restricted-globals': [
        'error',
        {
          name: 'localStorage',
          message:
            'Nothing from this app may be written to disk. See CLAUDE.md, "Personal data on the client".',
        },
        {
          name: 'sessionStorage',
          message:
            'Nothing from this app may be written to disk. See CLAUDE.md, "Personal data on the client".',
        },
      ],

      'no-restricted-syntax': [
        'error',
        {
          selector: 'TSEnumDeclaration',
          message: 'Enums are not erasable syntax. Use a union type or `as const` object.',
        },
        {
          selector: 'TSModuleDeclaration[kind="namespace"]',
          message: 'Namespaces are not erasable syntax. Use ES modules.',
        },
        /*
         * Locale date formatting silently uses the device's timezone. A
         * volunteer with a misconfigured laptop then sees every session at the
         * wrong time, and nothing anywhere reports an error. All formatting
         * goes through lib/london-time.ts, which pins Europe/London.
         */
        {
          selector: 'MemberExpression > Identifier.property[name=/^toLocale(Date|Time)?String$/]',
          message:
            'Formats in the device timezone. Use src/lib/london-time.ts — see CLAUDE.md, "Time is Europe/London wall clock".',
        },
      ],

      'no-restricted-imports': ['error', { patterns: [apiClientBoundary, workerBoundary] }],
    },
  },
  {
    // The data layer, the auth layer and each feature's query module are the
    // legitimate callers of the API client. The Worker boundary still holds for
    // them — it holds everywhere.
    files: ['src/api/**', 'src/auth/**', 'src/features/*/queries.ts'],
    rules: { 'no-restricted-imports': ['error', { patterns: [workerBoundary] }] },
  },
  {
    /*
     * From inside src/worker/, every path out of the directory starts with
     * `../`, so that is the whole of the reverse boundary. The Worker imports
     * nothing but the platform.
     */
    files: ['src/worker/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../*', '../**'],
              message:
                'The proxy Worker shares no code with the app — they compile against different globals. See CLAUDE.md, "The tsconfig split".',
            },
          ],
        },
      ],
    },
  },
  {
    // React-specific rules apply to the app, not to config or tooling.
    //
    // `configs.flat['recommended-latest']` rather than the top-level
    // `configs['recommended-latest']`: the latter is still the eslintrc shape
    // (plugins as an array), which eslint 10 rejects outright.
    files: ['src/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat['recommended-latest'], jsxA11y.flatConfigs.recommended],
    rules: {
      'react-refresh/only-export-components': 'warn',
    },
    plugins: { 'react-refresh': reactRefresh },
  },
  {
    files: ['src/lib/london-time.ts'],
    rules: {
      // The one module allowed to touch locale formatting: it pins the zone.
      'no-restricted-syntax': 'off',
    },
  },
  {
    files: ['**/*.d.ts'],
    rules: {
      'no-restricted-syntax': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
  {
    // Tests may reach for sharper tools than production code.
    files: ['test/**/*.{ts,tsx}', 'src/**/*.test.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
    },
  },
  {
    files: ['eslint.config.js'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    // Run by `npm run check` on a developer machine and in CI, never bundled.
    files: ['scripts/**/*.mjs'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      globals: { console: 'readonly', process: 'readonly' },
    },
    rules: { 'no-console': 'off' },
  },
  prettier,
);
