/** Foodbank configuration release source. Questionnaire conversion remains in questionnaire.gs. */
const RULES_SHEET = 'Rules';
const GENERATED_SHEET = 'Generated Rules JSON';
const GENERATED_RELEASE_SHEET = 'Generated Configuration Release';
const CONFIGURATION_VALIDATION_SHEET = 'Configuration validation';
const HEADER_ROW = 1;
const FIRST_DATA_ROW = 3;
const NEEDS_ATTENTION = 'Needs team-leader attention';
const COLUMNS = [
  ['questionKey', 'Preference key'],
  ['answer', 'Answer (optional)'],
  ['outcome', 'Outcome'],
  ['people', 'People'],
  ['atLeast', 'At least'],
  ['stock', 'Stock item'],
  ['quantity', 'Quantity'],
];

function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Foodbank configuration')
    .addItem('Validate configuration', 'validateConfigurationRelease')
    .addItem('Generate configuration release', 'generateConfigurationRelease')
    .addToUi();
}

/** Validates both authoring tabs without overwriting any generated JSON. */
function validateConfigurationRelease() {
  const release = buildConfigurationRelease_();
  writeConfigurationValidation_(release);
  showConfigurationToast_(
    release.errors.length === 0
      ? 'Configuration is valid. You can generate a configuration release.'
      : 'Configuration needs correction. See the Configuration validation tab.',
  );
}

function validateRules_() {
  const result = parseRules_();
  return {
    errors: result.errors.map((error) => `Rules: ${error}`),
    output: result.errors.length === 0 ? JSON.stringify({ rules: result.rules }, null, 2) : null,
  };
}

function writeRulesJson_(output) {
  const sheet = getOrCreateSheet_(GENERATED_SHEET);
  ensureSize_(sheet, 2, 1);
  sheet
    .getRange('A1')
    .setValue(
      'Generated by Foodbank configuration > Generate configuration release. Review before uploading.',
    )
    .setFontWeight('bold')
    .setBackground('#d9eaf7');
  sheet.getRange('A2').setValue(output).setWrapStrategy(SpreadsheetApp.WrapStrategy.WRAP);
  sheet.setColumnWidth(1, 720);
  sheet.setRowHeight(2, Math.min(Math.max(180, output.split('\n').length * 18), 800));
}

/**
 * Generates the uploadable pair in the required order: Rules first, then the
 * Questionnaire. The manifest is written only once both generated payloads
 * are present and has hashes which bind it to those exact cells.
 */
function generateConfigurationRelease() {
  const release = buildConfigurationRelease_();
  writeConfigurationValidation_(release);
  if (release.errors.length > 0) {
    showConfigurationToast_('Configuration needs correction. No JSON was generated.');
    return;
  }

  clearConfigurationReleaseManifest_();
  writeRulesJson_(release.rulesOutput);
  writeQuestionnaireJson_(release.questionnaireOutput);
  const manifest = createConfigurationReleaseManifest_(
    release.questionnaireOutput,
    release.rulesOutput,
  );
  writeConfigurationReleaseManifest_(manifest);
  showConfigurationToast_(
    `Configuration release generated at ${manifest.generatedAt}. Review both JSON tabs before uploading.`,
  );
}

function buildConfigurationRelease_() {
  const rules = validateRules_();
  const questionnaire = validateQuestionnaireConfig_();
  return {
    errors: rules.errors.concat(questionnaire.errors),
    rulesOutput: rules.output,
    questionnaireOutput: questionnaire.output,
    questionCount: questionnaire.questionCount,
    pageCount: questionnaire.pageCount,
  };
}

function writeConfigurationValidation_(release) {
  const sheet = getOrCreateSheet_(CONFIGURATION_VALIDATION_SHEET);
  const output =
    release.errors.length === 0
      ? `Configuration is valid: ${String(release.questionCount)} questions on ${String(release.pageCount)} pages.`
      : release.errors.map((error) => `• ${error}`).join('\n');
  ensureSize_(sheet, 2, 1);
  sheet
    .getRange('A1')
    .setValue('Configuration validation')
    .setFontWeight('bold')
    .setBackground('#d9eaf7');
  sheet.getRange('A2').setValue(output).setWrapStrategy(SpreadsheetApp.WrapStrategy.WRAP);
  sheet.setColumnWidth(1, 900);
  sheet.setRowHeight(2, Math.min(Math.max(60, output.split('\n').length * 18), 1600));
}

function showConfigurationToast_(message) {
  SpreadsheetApp.getActive().toast(message, 'Foodbank configuration', 10);
}

function createConfigurationReleaseManifest_(
  questionnaireOutput,
  rulesOutput,
  generatedAt,
  generationId,
) {
  return {
    version: 1,
    generationId: generationId === undefined ? Utilities.getUuid() : generationId,
    generatedAt: generatedAt === undefined ? new Date().toISOString() : generatedAt,
    questionnaireSha256: sha256Hex_(questionnaireOutput),
    rulesSha256: sha256Hex_(rulesOutput),
  };
}

function writeConfigurationReleaseManifest_(manifest) {
  const output = JSON.stringify(manifest, null, 2);
  const sheet = getOrCreateSheet_(GENERATED_RELEASE_SHEET);
  ensureSize_(sheet, 2, 1);
  sheet
    .getRange('A1')
    .setValue('Upload this manifest with the generated Rules and Questionnaire JSON.')
    .setFontWeight('bold')
    .setBackground('#d9eaf7');
  sheet.getRange('A2').setValue(output).setWrapStrategy(SpreadsheetApp.WrapStrategy.WRAP);
  sheet.setColumnWidth(1, 720);
  sheet.setRowHeight(2, Math.max(180, output.split('\n').length * 18));
}

/** Clears the prior release manifest immediately before replacing both payloads. */
function clearConfigurationReleaseManifest_() {
  const sheet = SpreadsheetApp.getActive().getSheetByName(GENERATED_RELEASE_SHEET);
  if (sheet !== null) sheet.getRange('A1:A2').clearContent();
}

function sha256Hex_(value) {
  return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, value, Utilities.Charset.UTF_8)
    .map((byte) => (byte & 0xff).toString(16).padStart(2, '0'))
    .join('');
}

function parseRules_() {
  const sheet = SpreadsheetApp.getActive().getSheetByName(RULES_SHEET);
  if (sheet === null) return { rules: [], errors: [`The ${RULES_SHEET} tab does not exist.`] };
  const headerErrors = validateHeaders_(sheet);
  if (headerErrors.length > 0) return { rules: [], errors: headerErrors };
  if (sheet.getLastRow() < FIRST_DATA_ROW)
    return { rules: [], errors: ['Add at least one rule row.'] };

  const rows = sheet
    .getRange(FIRST_DATA_ROW, 1, sheet.getLastRow() - FIRST_DATA_ROW + 1, COLUMNS.length)
    .getDisplayValues();
  const errors = [];
  const rules = [];
  let rule = null;
  let outcome = null;

  function finishRule() {
    if (rule === null) return;
    if (rule.otherwise === null)
      errors.push(`Rule starting on row ${rule.row}: every rule needs an Otherwise outcome.`);
    [...rule.cases, rule.otherwise].filter(Boolean).forEach((entry) => {
      if (entry.set.length === 0)
        errors.push(`Rule starting on row ${rule.row}: every outcome needs an item.`);
      const seen = new Set();
      entry.set.forEach((line) => {
        if (seen.has(line.stock))
          errors.push(
            `Rule starting on row ${rule.row}: ${line.stock} appears twice in one outcome.`,
          );
        seen.add(line.stock);
      });
    });
    rules.push(rule);
  }

  rows.forEach((row, index) => {
    const line = Object.fromEntries(
      COLUMNS.map(([key], column) => [key, String(row[column] || '').trim()]),
    );
    if (Object.values(line).every((value) => value === '')) return;
    const rowNumber = FIRST_DATA_ROW + index;
    if (line.questionKey !== '') {
      finishRule();
      rule = { row: rowNumber, when: { key: line.questionKey }, cases: [], otherwise: null };
      if (line.answer === '$selectedAnswer') {
        errors.push(`Row ${rowNumber}: $selectedAnswer is only valid in Stock item.`);
      } else if (line.answer !== '') {
        rule.when.hasAnswer = line.answer;
      }
      outcome = null;
    } else if (rule === null) {
      errors.push(`Row ${rowNumber}: the first rule row must name a preference key.`);
      return;
    } else if (line.answer !== '') {
      errors.push(
        `Row ${rowNumber}: repeat the preference key when starting a rule with a different answer.`,
      );
    }

    if (line.outcome !== '') {
      if (line.outcome === 'Case') {
        if (rule.otherwise !== null)
          errors.push(`Row ${rowNumber}: a Case cannot follow Otherwise in the same rule.`);
        const people = { Adults: 'adults', Children: 'children', Total: 'total' }[line.people];
        const atLeast = Number(line.atLeast);
        if (people === undefined)
          errors.push(`Row ${rowNumber}: Case needs People: Adults, Children or Total.`);
        if (line.atLeast === '' || !Number.isInteger(atLeast) || atLeast < 0)
          errors.push(
            `Row ${rowNumber}: Case needs a whole-number At least value of zero or more.`,
          );
        outcome =
          people === undefined || line.atLeast === '' || !Number.isInteger(atLeast) || atLeast < 0
            ? null
            : { familySize: { people, atLeast }, set: [] };
        if (outcome !== null) rule.cases.push(outcome);
      } else if (line.outcome === 'Otherwise') {
        if (line.people !== '' || line.atLeast !== '')
          errors.push(`Row ${rowNumber}: Otherwise cannot have People or At least values.`);
        if (rule.otherwise !== null)
          errors.push(`Row ${rowNumber}: a rule can have only one Otherwise outcome.`);
        outcome = { set: [] };
        rule.otherwise = outcome;
      } else {
        errors.push(`Row ${rowNumber}: Outcome must be Case or Otherwise.`);
        outcome = null;
      }
    } else {
      if (outcome === null) errors.push(`Row ${rowNumber}: start the rule with Case or Otherwise.`);
      if (line.people !== '' || line.atLeast !== '')
        errors.push(
          `Row ${rowNumber}: leave People and At least blank when adding another item to the same outcome.`,
        );
    }

    if (line.stock === '') errors.push(`Row ${rowNumber}: Stock item is required.`);
    if (line.quantity === '') errors.push(`Row ${rowNumber}: Quantity is required.`);
    const quantity = line.quantity === NEEDS_ATTENTION ? -1 : Number(line.quantity);
    if (
      line.quantity !== '' &&
      quantity !== -1 &&
      (!Number.isInteger(quantity) || quantity < 1 || quantity > 10)
    )
      errors.push(`Row ${rowNumber}: Quantity must be 1 to 10 or ${NEEDS_ATTENTION}.`);
    if (
      outcome !== null &&
      line.stock !== '' &&
      line.quantity !== '' &&
      (quantity === -1 || (Number.isInteger(quantity) && quantity >= 1 && quantity <= 10))
    )
      outcome.set.push({ stock: line.stock, quantity });
  });
  finishRule();
  return {
    rules: errors.length === 0 ? rules.map(({ row, ...rule }) => rule) : [],
    errors: errors.length === 0 && rules.length === 0 ? ['Add at least one rule row.'] : errors,
  };
}

function validateHeaders_(sheet) {
  const headers = sheet.getRange(HEADER_ROW, 1, 1, COLUMNS.length).getDisplayValues()[0];
  return COLUMNS.flatMap(([key], index) =>
    headers[index] === key
      ? []
      : [`Rules row 1 column ${index + 1} must be ${key}. Correct the header before validating.`],
  );
}

function getOrCreateSheet_(name) {
  const spreadsheet = SpreadsheetApp.getActive();
  return spreadsheet.getSheetByName(name) || spreadsheet.insertSheet(name);
}

function ensureSize_(sheet, rows, columns) {
  if (sheet.getMaxRows() < rows)
    sheet.insertRowsAfter(sheet.getMaxRows(), rows - sheet.getMaxRows());
  if (sheet.getMaxColumns() < columns)
    sheet.insertColumnsAfter(sheet.getMaxColumns(), columns - sheet.getMaxColumns());
}
